---
- name: Create app directory
  sudo: yes
  file: path={{ app_dir }} owner=root group=root mode=0755 state=directory

- name: Create app virtualenv directory
  sudo: yes
  file: path={{ venv_dir }} owner=root group=root mode=0755 state=directory

- name: Create virtualenv
  shell: virtualenv --python=/usr/bin/python{{ python_version }} --no-site-packages --distribute {{ venv_dir }}

- name: Install python requirements
  shell: "{{ venv_dir }}/bin/pip install -r {{ app_dir }}/{{ python_requirements }}"
